import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Loading from './Components/Loading'
import { Suspense } from 'react'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Suspense fallback={<Loading size={350}/>}>
      <body className={inter.className}>
    {children}
    
        </body>
        </Suspense>
    </html>
  )
}
